apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "chartinstaller.fullname" . }}
  namespace: {{ .Values.targetNamespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "chartinstaller.serviceAccountName" . }}
  namespace:  {{ .Release.Namespace }}
  # apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ include "chartinstaller.fullname" . }}
  apiGroup: rbac.authorization.k8s.io