# https://taskfile.dev

version: '3'

vars:
  VERSION: 0.3.0

tasks:
  build:
    cmds:
      - docker build -t zsfarkas/chartinstaller:{{.VERSION}} -t zsfarkas/chartinstaller:latest --target final .
  push-docker:
    cmds:
      - docker push zsfarkas/chartinstaller:{{.VERSION}}
      - docker push zsfarkas/chartinstaller:latest
  push-helm:
    dir: helm/chartinstaller
    cmds:
      - helm dep update
      - helm lint .
      - helm package . --version {{.VERSION}}
  install:
    dir: helm/chartinstaller
    cmds:
      - helm upgrade chartinstaller -n chartinstaller -i --create-namespace .
  uninstall:
    cmds:
      - helm uninstall chartinstaller -n chartinstaller
  default:
    cmds:
    - task: build
    - task: push-docker
    - task: push-helm
